# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'paint.ui'
##
## Created by: Qt User Interface Compiler version 6.9.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QDoubleSpinBox,
    QGroupBox, QHBoxLayout, QLabel, QMainWindow,
    QMenu, QMenuBar, QPushButton, QRadioButton,
    QSizePolicy, QSlider, QSpinBox, QStackedWidget,
    QStatusBar, QTextEdit, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1092, 878)
        MainWindow.setMinimumSize(QSize(1092, 878))
        MainWindow.setMaximumSize(QSize(1092, 878))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(530, 550, 551, 271))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 20, 49, 16))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 140, 49, 16))
        self.posEdit = QTextEdit(self.groupBox)
        self.posEdit.setObjectName(u"posEdit")
        self.posEdit.setGeometry(QRect(20, 40, 511, 91))
        self.negEdit = QTextEdit(self.groupBox)
        self.negEdit.setObjectName(u"negEdit")
        self.negEdit.setGeometry(QRect(20, 160, 511, 91))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 550, 511, 271))
        self.doubleSpinBox_guidance = QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_guidance.setObjectName(u"doubleSpinBox_guidance")
        self.doubleSpinBox_guidance.setGeometry(QRect(230, 20, 82, 24))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(170, 20, 49, 16))
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(30, 80, 49, 16))
        self.spinBox_step = QSpinBox(self.groupBox_2)
        self.spinBox_step.setObjectName(u"spinBox_step")
        self.spinBox_step.setGeometry(QRect(350, 20, 67, 24))
        self.spinBox_step.setMinimum(-1)
        self.label_5 = QLabel(self.groupBox_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(320, 20, 31, 16))
        self.spinBox_seed = QSpinBox(self.groupBox_2)
        self.spinBox_seed.setObjectName(u"spinBox_seed")
        self.spinBox_seed.setGeometry(QRect(60, 20, 101, 24))
        self.spinBox_seed.setMaximum(65535)
        self.checkBox_seed = QCheckBox(self.groupBox_2)
        self.checkBox_seed.setObjectName(u"checkBox_seed")
        self.checkBox_seed.setGeometry(QRect(10, 20, 51, 20))
        self.groupBox_3 = QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 50, 261, 201))
        self.checkBox_cnet = QCheckBox(self.groupBox_3)
        self.checkBox_cnet.setObjectName(u"checkBox_cnet")
        self.checkBox_cnet.setGeometry(QRect(10, 30, 78, 20))
        self.pushButton_previeweffect = QPushButton(self.groupBox_3)
        self.pushButton_previeweffect.setObjectName(u"pushButton_previeweffect")
        self.pushButton_previeweffect.setGeometry(QRect(80, 180, 101, 20))
        self.comboBox_cnetcp = QComboBox(self.groupBox_3)
        self.comboBox_cnetcp.addItem(u"canny")
        self.comboBox_cnetcp.addItem(u"ip2p")
        self.comboBox_cnetcp.addItem(u"inpaint")
        self.comboBox_cnetcp.addItem(u"mlsd")
        self.comboBox_cnetcp.addItem(u"depth")
        self.comboBox_cnetcp.addItem(u"normalbae")
        self.comboBox_cnetcp.addItem(u"seg")
        self.comboBox_cnetcp.addItem(u"lineart")
        self.comboBox_cnetcp.addItem(u"lineart_anime")
        self.comboBox_cnetcp.addItem(u"openpose")
        self.comboBox_cnetcp.addItem(u"scribble")
        self.comboBox_cnetcp.addItem(u"softedge")
        self.comboBox_cnetcp.addItem(u"shuffle")
        self.comboBox_cnetcp.addItem(u"tile")
        self.comboBox_cnetcp.setObjectName(u"comboBox_cnetcp")
        self.comboBox_cnetcp.setGeometry(QRect(80, 20, 171, 24))
        self.stackedWidget_cnet = QStackedWidget(self.groupBox_3)
        self.stackedWidget_cnet.setObjectName(u"stackedWidget_cnet")
        self.stackedWidget_cnet.setGeometry(QRect(10, 50, 241, 121))
        self.page_none = QWidget()
        self.page_none.setObjectName(u"page_none")
        self.stackedWidget_cnet.addWidget(self.page_none)
        self.page_canny = QWidget()
        self.page_canny.setObjectName(u"page_canny")
        self.spinBox_thlow = QSpinBox(self.page_canny)
        self.spinBox_thlow.setObjectName(u"spinBox_thlow")
        self.spinBox_thlow.setGeometry(QRect(166, 20, 71, 24))
        self.spinBox_thlow.setMinimum(1)
        self.spinBox_thlow.setMaximum(1000)
        self.spinBox_thlow.setValue(100)
        self.spinBox_thhigh = QSpinBox(self.page_canny)
        self.spinBox_thhigh.setObjectName(u"spinBox_thhigh")
        self.spinBox_thhigh.setGeometry(QRect(166, 50, 71, 24))
        self.spinBox_thhigh.setMinimum(1)
        self.spinBox_thhigh.setMaximum(200)
        self.spinBox_thhigh.setValue(200)
        self.label_6 = QLabel(self.page_canny)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(80, 20, 91, 20))
        self.label_7 = QLabel(self.page_canny)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(80, 50, 91, 20))
        self.checkBox_Blur = QCheckBox(self.page_canny)
        self.checkBox_Blur.setObjectName(u"checkBox_Blur")
        self.checkBox_Blur.setGeometry(QRect(0, 70, 51, 20))
        self.checkBox_Quant = QCheckBox(self.page_canny)
        self.checkBox_Quant.setObjectName(u"checkBox_Quant")
        self.checkBox_Quant.setGeometry(QRect(0, 100, 61, 20))
        self.spinBox_Blur = QSpinBox(self.page_canny)
        self.spinBox_Blur.setObjectName(u"spinBox_Blur")
        self.spinBox_Blur.setGeometry(QRect(60, 70, 67, 24))
        self.spinBox_Blur.setMinimum(1)
        self.spinBox_Blur.setMaximum(100)
        self.spinBox_Blur.setValue(3)
        self.spinBox_Quant = QSpinBox(self.page_canny)
        self.spinBox_Quant.setObjectName(u"spinBox_Quant")
        self.spinBox_Quant.setGeometry(QRect(60, 100, 67, 24))
        self.spinBox_Quant.setMinimum(1)
        self.spinBox_Quant.setMaximum(255)
        self.spinBox_Quant.setValue(2)
        self.checkBox_Bayer = QCheckBox(self.page_canny)
        self.checkBox_Bayer.setObjectName(u"checkBox_Bayer")
        self.checkBox_Bayer.setGeometry(QRect(140, 100, 91, 20))
        self.stackedWidget_cnet.addWidget(self.page_canny)
        self.page_inpaint = QWidget()
        self.page_inpaint.setObjectName(u"page_inpaint")
        self.doubleSpinBox_eta = QDoubleSpinBox(self.page_inpaint)
        self.doubleSpinBox_eta.setObjectName(u"doubleSpinBox_eta")
        self.doubleSpinBox_eta.setGeometry(QRect(170, 20, 71, 24))
        self.doubleSpinBox_eta.setMinimum(0.010000000000000)
        self.doubleSpinBox_eta.setMaximum(1.000000000000000)
        self.doubleSpinBox_eta.setSingleStep(0.010000000000000)
        self.doubleSpinBox_eta.setValue(1.000000000000000)
        self.label_10 = QLabel(self.page_inpaint)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(150, 20, 21, 20))
        self.stackedWidget_cnet.addWidget(self.page_inpaint)
        self.page_openpose = QWidget()
        self.page_openpose.setObjectName(u"page_openpose")
        self.comboBox_alias = QComboBox(self.page_openpose)
        self.comboBox_alias.addItem("")
        self.comboBox_alias.addItem("")
        self.comboBox_alias.addItem("")
        self.comboBox_alias.addItem("")
        self.comboBox_alias.addItem("")
        self.comboBox_alias.addItem("")
        self.comboBox_alias.setObjectName(u"comboBox_alias")
        self.comboBox_alias.setGeometry(QRect(139, 20, 101, 24))
        self.label_12 = QLabel(self.page_openpose)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(110, 20, 31, 20))
        self.spinBox_radius = QSpinBox(self.page_openpose)
        self.spinBox_radius.setObjectName(u"spinBox_radius")
        self.spinBox_radius.setGeometry(QRect(50, 50, 67, 24))
        self.spinBox_radius.setMinimum(1)
        self.spinBox_radius.setMaximum(10)
        self.spinBox_radius.setValue(4)
        self.label_13 = QLabel(self.page_openpose)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(10, 50, 41, 20))
        self.spinBox_thickness = QSpinBox(self.page_openpose)
        self.spinBox_thickness.setObjectName(u"spinBox_thickness")
        self.spinBox_thickness.setGeometry(QRect(180, 50, 61, 24))
        self.spinBox_thickness.setMinimum(1)
        self.spinBox_thickness.setMaximum(10)
        self.label_14 = QLabel(self.page_openpose)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(128, 50, 51, 20))
        self.doubleSpinBox_kptthr = QDoubleSpinBox(self.page_openpose)
        self.doubleSpinBox_kptthr.setObjectName(u"doubleSpinBox_kptthr")
        self.doubleSpinBox_kptthr.setGeometry(QRect(160, 80, 82, 24))
        self.doubleSpinBox_kptthr.setMaximum(1.000000000000000)
        self.doubleSpinBox_kptthr.setSingleStep(0.010000000000000)
        self.doubleSpinBox_kptthr.setValue(0.500000000000000)
        self.label_15 = QLabel(self.page_openpose)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(118, 80, 41, 21))
        self.stackedWidget_cnet.addWidget(self.page_openpose)
        self.page_shuffle = QWidget()
        self.page_shuffle.setObjectName(u"page_shuffle")
        self.spinBox_shufflek = QSpinBox(self.page_shuffle)
        self.spinBox_shufflek.setObjectName(u"spinBox_shufflek")
        self.spinBox_shufflek.setGeometry(QRect(170, 20, 67, 24))
        self.spinBox_shufflek.setMinimum(1)
        self.spinBox_shufflek.setMaximum(100)
        self.spinBox_shufflek.setSingleStep(5)
        self.spinBox_shufflek.setValue(5)
        self.label_16 = QLabel(self.page_shuffle)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(118, 20, 51, 21))
        self.checkBox_Block = QCheckBox(self.page_shuffle)
        self.checkBox_Block.setObjectName(u"checkBox_Block")
        self.checkBox_Block.setGeometry(QRect(60, 50, 51, 20))
        self.spinBox_blockk = QSpinBox(self.page_shuffle)
        self.spinBox_blockk.setObjectName(u"spinBox_blockk")
        self.spinBox_blockk.setGeometry(QRect(170, 50, 67, 24))
        self.spinBox_blockk.setMinimum(1)
        self.spinBox_blockk.setMaximum(9)
        self.spinBox_blockk.setValue(6)
        self.label_17 = QLabel(self.page_shuffle)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(120, 50, 41, 21))
        self.stackedWidget_cnet.addWidget(self.page_shuffle)
        self.page_tile = QWidget()
        self.page_tile.setObjectName(u"page_tile")
        self.doubleSpinBox_strength = QDoubleSpinBox(self.page_tile)
        self.doubleSpinBox_strength.setObjectName(u"doubleSpinBox_strength")
        self.doubleSpinBox_strength.setGeometry(QRect(150, 20, 82, 24))
        self.doubleSpinBox_strength.setMaximum(1.000000000000000)
        self.doubleSpinBox_strength.setSingleStep(0.010000000000000)
        self.doubleSpinBox_strength.setValue(1.000000000000000)
        self.label_18 = QLabel(self.page_tile)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(100, 20, 51, 21))
        self.stackedWidget_cnet.addWidget(self.page_tile)
        self.groupBox_4 = QGroupBox(self.groupBox_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(280, 50, 221, 201))
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 20, 31, 16))
        self.horizontalSlider_penbold = QSlider(self.groupBox_4)
        self.horizontalSlider_penbold.setObjectName(u"horizontalSlider_penbold")
        self.horizontalSlider_penbold.setGeometry(QRect(60, 20, 151, 22))
        self.horizontalSlider_penbold.setMinimum(1)
        self.horizontalSlider_penbold.setMaximum(100)
        self.horizontalSlider_penbold.setPageStep(1)
        self.horizontalSlider_penbold.setValue(10)
        self.horizontalSlider_penbold.setOrientation(Qt.Orientation.Horizontal)
        self.groupBox_5 = QGroupBox(self.groupBox_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 110, 201, 80))
        self.radioButton_free = QRadioButton(self.groupBox_5)
        self.radioButton_free.setObjectName(u"radioButton_free")
        self.radioButton_free.setGeometry(QRect(10, 20, 51, 20))
        self.radioButton_free.setChecked(True)
        self.radioButton_circle = QRadioButton(self.groupBox_5)
        self.radioButton_circle.setObjectName(u"radioButton_circle")
        self.radioButton_circle.setGeometry(QRect(60, 20, 51, 20))
        self.radioButton_ellipse = QRadioButton(self.groupBox_5)
        self.radioButton_ellipse.setObjectName(u"radioButton_ellipse")
        self.radioButton_ellipse.setGeometry(QRect(120, 20, 61, 20))
        self.radioButton_line = QRadioButton(self.groupBox_5)
        self.radioButton_line.setObjectName(u"radioButton_line")
        self.radioButton_line.setGeometry(QRect(10, 50, 61, 20))
        self.radioButton_square = QRadioButton(self.groupBox_5)
        self.radioButton_square.setObjectName(u"radioButton_square")
        self.radioButton_square.setGeometry(QRect(60, 50, 61, 20))
        self.radioButton_erase = QRadioButton(self.groupBox_5)
        self.radioButton_erase.setObjectName(u"radioButton_erase")
        self.radioButton_erase.setGeometry(QRect(120, 50, 92, 20))
        self.groupBox_6 = QGroupBox(self.groupBox_4)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 60, 201, 51))
        self.checkBox_fillenable = QCheckBox(self.groupBox_6)
        self.checkBox_fillenable.setObjectName(u"checkBox_fillenable")
        self.checkBox_fillenable.setGeometry(QRect(10, 20, 78, 20))
        self.radioButton_filldraw = QRadioButton(self.groupBox_6)
        self.radioButton_filldraw.setObjectName(u"radioButton_filldraw")
        self.radioButton_filldraw.setGeometry(QRect(70, 20, 51, 20))
        self.radioButton_filldraw.setChecked(True)
        self.radioButton_fillbase = QRadioButton(self.groupBox_6)
        self.radioButton_fillbase.setObjectName(u"radioButton_fillbase")
        self.radioButton_fillbase.setGeometry(QRect(120, 20, 61, 20))
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 40, 31, 16))
        self.verticalLayoutWidget = QWidget(self.groupBox_4)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(50, 40, 161, 21))
        self.verticalLayout_color = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_color.setObjectName(u"verticalLayout_color")
        self.verticalLayout_color.setContentsMargins(0, 0, 0, 0)
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 250, 49, 16))
        self.label_staus = QLabel(self.groupBox_2)
        self.label_staus.setObjectName(u"label_staus")
        self.label_staus.setGeometry(QRect(60, 250, 101, 16))
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(10, 9, 1071, 541))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.horizontalLayoutWidget.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1092, 33))
        self.menusave = QMenu(self.menubar)
        self.menusave.setObjectName(u"menusave")
        self.menuopen = QMenu(self.menubar)
        self.menuopen.setObjectName(u"menuopen")
        self.menuclear = QMenu(self.menubar)
        self.menuclear.setObjectName(u"menuclear")
        self.menugenerate = QMenu(self.menubar)
        self.menugenerate.setObjectName(u"menugenerate")
        self.menuload = QMenu(self.menubar)
        self.menuload.setObjectName(u"menuload")
        self.menuoptions = QMenu(self.menubar)
        self.menuoptions.setObjectName(u"menuoptions")
        self.menuhelp = QMenu(self.menubar)
        self.menuhelp.setObjectName(u"menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menusave.menuAction())
        self.menubar.addAction(self.menuopen.menuAction())
        self.menubar.addAction(self.menuclear.menuAction())
        self.menubar.addAction(self.menugenerate.menuAction())
        self.menubar.addAction(self.menuload.menuAction())
        self.menubar.addAction(self.menuoptions.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)

        self.stackedWidget_cnet.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Prompt", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Positive", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Negative", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Parameter", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"guidance", None))
        self.label_4.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"step", None))
        self.checkBox_seed.setText(QCoreApplication.translate("MainWindow", u"seed", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"ControlNet", None))
        self.checkBox_cnet.setText(QCoreApplication.translate("MainWindow", u"enable", None))
        self.pushButton_previeweffect.setText(QCoreApplication.translate("MainWindow", u"Preview Effect", None))

        self.spinBox_thlow.setSuffix("")
        self.spinBox_thlow.setPrefix("")
        self.spinBox_thhigh.setSuffix("")
        self.spinBox_thhigh.setPrefix("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Threshold Low", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Threshold High", None))
        self.checkBox_Blur.setText(QCoreApplication.translate("MainWindow", u"Blur", None))
        self.checkBox_Quant.setText(QCoreApplication.translate("MainWindow", u"Quant", None))
        self.checkBox_Bayer.setText(QCoreApplication.translate("MainWindow", u"Bayer Pattern", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"eta", None))
        self.comboBox_alias.setItemText(0, QCoreApplication.translate("MainWindow", u"animal", None))
        self.comboBox_alias.setItemText(1, QCoreApplication.translate("MainWindow", u"human", None))
        self.comboBox_alias.setItemText(2, QCoreApplication.translate("MainWindow", u"body26", None))
        self.comboBox_alias.setItemText(3, QCoreApplication.translate("MainWindow", u"face", None))
        self.comboBox_alias.setItemText(4, QCoreApplication.translate("MainWindow", u"hand", None))
        self.comboBox_alias.setItemText(5, QCoreApplication.translate("MainWindow", u"wholebody", None))

        self.label_12.setText(QCoreApplication.translate("MainWindow", u"alias", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"radius", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"thickness", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"kpt_thr", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"shuffle_k", None))
        self.checkBox_Block.setText(QCoreApplication.translate("MainWindow", u"Block", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"block_k", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"strength", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"PenTool", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Bold", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("MainWindow", u"Mode", None))
        self.radioButton_free.setText(QCoreApplication.translate("MainWindow", u"free", None))
        self.radioButton_circle.setText(QCoreApplication.translate("MainWindow", u"circle", None))
        self.radioButton_ellipse.setText(QCoreApplication.translate("MainWindow", u"ellipse", None))
        self.radioButton_line.setText(QCoreApplication.translate("MainWindow", u"line", None))
        self.radioButton_square.setText(QCoreApplication.translate("MainWindow", u"square", None))
        self.radioButton_erase.setText(QCoreApplication.translate("MainWindow", u"erase", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("MainWindow", u"Fill", None))
        self.checkBox_fillenable.setText(QCoreApplication.translate("MainWindow", u"enable", None))
        self.radioButton_filldraw.setText(QCoreApplication.translate("MainWindow", u"draw", None))
        self.radioButton_fillbase.setText(QCoreApplication.translate("MainWindow", u"base", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Color", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"status:", None))
        self.label_staus.setText("")
        self.menusave.setTitle(QCoreApplication.translate("MainWindow", u"save", None))
        self.menuopen.setTitle(QCoreApplication.translate("MainWindow", u"open", None))
        self.menuclear.setTitle(QCoreApplication.translate("MainWindow", u"clear", None))
        self.menugenerate.setTitle(QCoreApplication.translate("MainWindow", u"generate", None))
        self.menuload.setTitle(QCoreApplication.translate("MainWindow", u"load", None))
        self.menuoptions.setTitle(QCoreApplication.translate("MainWindow", u"options", None))
        self.menuhelp.setTitle(QCoreApplication.translate("MainWindow", u"help", None))
    # retranslateUi

